### ISSUE TITLE
Not cloning all repositories 

### ISSUE THREAD

**Issue by jfiksel** [konzy/mass_clone#2]
I'm trying to use the `clone_all_helper_example.sh` script to mass clone repositories from my organization. However, it seems to max out at 36 repositories, when there are much more. Is there a way to bypass this limit?

**Comment by konzy** [comment]
When I first wrote the script it seemed like it was working across multiple pages as we too had over 100 repos.  Conceivably, they could have changed something that the previous logic no longer works.  I just merged your pull request that at first glance looks to have changed the logic for grabbing all the pages.  Thanks for the pull request.  Closing issue.
