### ISSUE TITLE
Error with more than 2 pages of repos / Line 52

### ISSUE THREAD

**Issue by bsiever** [konzy/mass_clone#5]
Line 52 should be:
numRepos=$(echo "$tempJSON" | grep -o "full_name" | wc -l)
not:
numRepos=$(echo "$rawJSON" | grep -o "full_name" | wc -l)

I.e., if there are 100 repos in the current page (not 100 total, which would always stop at 2 pages)
  Bill

**Comment by konzy** [comment]
Made the change.  Thanks.

**Comment by bsiever** [comment]
Thank you for sharing your script!  Saved me a bit of time/effort.
